name: Publish Alpha by Tag

on:
  push:
    tags:
      - 'v*-alpha*'
      - 'v*-beta*'
      - 'v*-rc*'

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Determine npm tag
        id: npm_tag
        run: |
          if [[ "${{ steps.version.outputs.VERSION }}" == *"alpha"* ]]; then
            echo "TAG=alpha" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.version.outputs.VERSION }}" == *"beta"* ]]; then
            echo "TAG=beta" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.version.outputs.VERSION }}" == *"rc"* ]]; then
            echo "TAG=rc" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi
      
      - name: Update package.json version
        run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
      
      - name: Build for production
        run: npm run build
      
      - name: Publish to NPM
        run: cd dist && npm publish --tag ${{ steps.npm_tag.outputs.TAG }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
